// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace CDatos.Migrations
{
    [DbContext(typeof(VeterinariaContext))]
    [Migration("20250421144712_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("en_US.UTF-8")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CDatos.Entidades.AnimalAtendido", b =>
                {
                    b.Property<int>("IdAnimalatendido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnimalatendido"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("IdDuenoAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnimalatendido")
                        .HasName("PK_ID_ANIMALATENDIDO");

                    b.HasIndex("IdDuenoAnimal");

                    b.ToTable("AnimalAtendido");
                });

            modelBuilder.Entity("CDatos.Entidades.Atencion", b =>
                {
                    b.Property<int>("IdAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtencion"));

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAnimalAtendido")
                        .HasColumnType("int");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAtencion")
                        .HasName("PK_ID_ATENCION");

                    b.HasIndex("IdAnimalAtendido");

                    b.ToTable("Atencion");
                });

            modelBuilder.Entity("CDatos.Entidades.DuenoAnimal", b =>
                {
                    b.Property<int>("IdDuenoAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDuenoAnimal"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDuenoAnimal")
                        .HasName("PK_ID_DUENOANIMAL");

                    b.ToTable("DuenoAnimal");
                });

            modelBuilder.Entity("CDatos.Entidades.AnimalAtendido", b =>
                {
                    b.HasOne("CDatos.Entidades.DuenoAnimal", "DuenoAnimal")
                        .WithMany("AnimalAtendido")
                        .HasForeignKey("IdDuenoAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuenoAnimal");
                });

            modelBuilder.Entity("CDatos.Entidades.Atencion", b =>
                {
                    b.HasOne("CDatos.Entidades.AnimalAtendido", "AnimalAtendido")
                        .WithMany("Atencion")
                        .HasForeignKey("IdAnimalAtendido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalAtendido");
                });

            modelBuilder.Entity("CDatos.Entidades.AnimalAtendido", b =>
                {
                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("CDatos.Entidades.DuenoAnimal", b =>
                {
                    b.Navigation("AnimalAtendido");
                });
#pragma warning restore 612, 618
        }
    }
}
